# Generated by Django 3.0.8 on 2020-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mame', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MakeTea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(verbose_name='Amount of water')),
                ('temp', models.IntegerField(verbose_name='Temperature')),
                ('typeoftea', models.CharField(choices=[('BL', 'black'), ('GT', 'green'), ('OO', 'oolong'), ('WH', 'white'), ('PU', 'puer'), ('EG', 'earl grey'), ('JS', 'jasmine'), ('MS', 'massala'), ('FT', 'fruit'), ('FL', 'flower'), ('LF', 'leaf')], default='BL', max_length=255, verbose_name='Preference type of tea')),
                ('adds', models.ManyToManyField(related_name='adds_tea', to='api.Add')),
            ],
        ),
    ]
