# Generated by Django 3.0.8 on 2020-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='mame',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='maketea',
            name='temp',
            field=models.PositiveIntegerField(verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='maketea',
            name='water',
            field=models.PositiveIntegerField(verbose_name='Amount of water'),
        ),
    ]
